//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEndServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audience
    {
        public string ClientId { get; set; }
        public string Secret { get; set; }
        public string ClientName { get; set; }
        public string Issuer { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public short StatusCode { get; set; }
    }
}
